name: 'Notion Page Updater'
description: 'Adds icons and cover images to new Notion pages'
inputs:
  notion_api_key:
    description: 'Notion API Key'
    required: true
  notion_database_id:
    description: 'Notion Database ID'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'